[book]
author = "sitandr"
language = "en"
multilingual = false
src = "src"
title = "Typst Examples Book"

[preprocessor.typst-highlight]
#disable_inline = true
typst_default = true
render = true
warn_not_specified = true

[output.html]
additional-css = ["./theme/mdbook-pagetoc/style.css"]
additional-js = ["./theme/mdbook-pagetoc/sidebar.js", "./theme/popup/popup.js"]
git-repository-url = "https://github.com/sitandr/typst-examples-book"

[output.html.redirect]
"/snippets/hidding.html" = "./hiding.html"
